#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${TEMPORAL_DB_USER} WITH PASSWORD '${TEMPORAL_DB_PASS}';
    CREATE DATABASE ${TEMPORAL_DB_USER} OWNER ${TEMPORAL_DB_USER};
    CREATE DATABASE ${TEMPORAL_DB_USER}_visibility OWNER ${TEMPORAL_DB_USER};
EOSQL
