log:
  level: debug

runner:
  capacity: 1
  timeout: 3h
  labels:
    - "ubuntu-latest:docker://catthehacker/ubuntu:act-latest"
    - "ubuntu-22.04:docker://catthehacker/ubuntu:act-latest"

container:
  network: aigion_default
  valid_volumes:
    - /var/run/docker.sock

cache:
  enabled: false
